import Agentsidebar from "@/components/agent/agentSidebar";
import ProtectedRouter from "@/components/agent/ProtectedRouter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Heaven Finder User",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRouter>
      <div className="flex bg-gray-100">
        <Agentsidebar />
        <div className="fleX p-3 w-full">{children}</div>
      </div>
    </ProtectedRouter>
  );
}
