import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Navbar";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Heaven finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
       <Header/>
        {children}
        </Providers>
      </body>
    </html>
  );
}
