import AdminNavbar from "@/components/admin/AdminNavbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Heaven finder user",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <AdminNavbar/>
      {children}
 
    </>
  );
}