import type { Metadata } from "next";
import Header from "@/components/user/Navbar";
import Footer from "@/components/user/Footer";

export const metadata: Metadata = {
  title: "Heaven finder user",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />{children}<Footer />
    </>
  );
}
