import type { Metadata } from "next";
import Header from "@/components/user/Navbar";
import Footer from "@/components/user/Footer";
import ProtectedRouter from "@/components/user/protuctedRouter";

export const metadata: Metadata = {
  title: "Heaven finder user",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ProtectedRouter>
        <Header />
        {children}
        <Footer />
      </ProtectedRouter>
    </>
  );
}
